again fixed dockerfile for jenkins build issue

diff --git a/clg-frontend/Dockerfile b/clg-frontend/Dockerfile
--- a/clg-frontend/Dockerfile
+++ b/clg-frontend/Dockerfile
@@ -9,18 +9,19 @@ WORKDIR /app
 # Install dependencies based on the preferred package manager
 COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* ./
 
-RUN \
-  if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
-  elif [ -f package-lock.json ]; then npm ci; \
-  elif [ -f pnpm-lock.yaml ]; then npm i pnpm -g && pnpm i --frozen-lockfile; \
-  else echo "Lockfile not found." && exit 1; \
-  fi
 # RUN \
 #   if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
 #   elif [ -f package-lock.json ]; then npm ci; \
-#   elif [ -f pnpm-lock.yaml ]; then yarn global add pnpm && pnpm i --frozen-lockfile; \
+#   elif [ -f pnpm-lock.yaml ]; then npm i pnpm -g && pnpm i --frozen-lockfile; \
 #   else echo "Lockfile not found." && exit 1; \
 #   fi
+
+RUN \
+  if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
+  elif [ -f package-lock.json ]; then npm ci; \
+  elif [ -f pnpm-lock.yaml ]; then yarn global add pnpm && pnpm i --frozen-lockfile; \
+  else echo "Lockfile not found." && exit 1; \
+  fi
 
 
 # Rebuild the source code only when needed
@@ -39,6 +40,7 @@ COPY . .
 # If using npm comment out above and use below instead
 # RUN npm install -g npm@10.2.5
 # RUN npm run build
+RUN yarn global add pnpm@latest
 RUN pnpm run build
 
 # Production image, copy all the files and run next
